In [1]:
import numpy as np

In [2]:
print(np.version)

<module 'numpy.version' from 'C:\\Users\\shyam\\anaconda3\\Lib\\site-packages\\numpy\\version.py'>


In [7]:
# 1d array 

arr=np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [12]:
#2d array 

arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)


[[1 2 3]
 [4 5 6]]


In [19]:
# higer array
arr=np.array([10,20,30,40],ndmin=5)
print(arr)

[[[[[10 20 30 40]]]]]


In [20]:
#array slicing 
arr=np.array([1,2,3,4,5])
print(arr[1:5])
print(arr[-4:-2])

[2 3 4 5]
[2 3]


In [29]:
#insert() : insert values at given places

a=np.array([1,2,3,4,5])
a=np.insert(a,4,100) # ( array_variable , loaction , insert_value)
print(a)

[  1   2   3   4 100   5]


In [30]:
arr = np.array([1,2,3,4,5])
x=arr.copy()

arr[0] = 42  # arr will only change 
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [31]:
arr = np.array([1,2,3,4,5])
x=arr.view()  # if we use view then in both the arrays the values get changed 
print(x)
arr[0] = 42
print(arr)
print(x)

[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [35]:
#joining numpy array 

arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

arr=np.concatenate((arr1,arr2))
print(arr)


[1 2 3 4 5 6]


In [39]:
# using stack function 
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,50])
arr = np.stack((arr1,arr2),axis=0)
arr3 = np.stack((arr1,arr2),axis=1)

print(arr)
print(arr3)

[[10 20 30]
 [40 50 50]]
[[10 40]
 [20 50]
 [30 50]]


In [43]:
#spliting the array 
arr = np.array([1,2,3,4,5,6])
new=np.array_split(arr,2) # (variable,in how many times u want to split)
print(new)

[array([1, 2, 3]), array([4, 5, 6])]


In [47]:
# searching in array 

arr = np.array([10,20,30,40,55,65,4])
x=np.where(arr == 55)
x1=np.where(arr == 5)
y=np.where(arr%2 == 0)
z=np.where(arr%2 == 1)
print(x)
print(y)
print(z)
print(x1)

(array([4]),)
(array([0, 1, 2, 3, 6]),)
(array([4, 5]),)
(array([], dtype=int64),)


In [48]:
# sorting array 
arr = np.array([3, 2, 0, 1])
arr1 = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))
print(np.sort(arr1))


[0 1 2 3]
['apple' 'banana' 'cherry']
